services:
  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  metricas:
    build: ./metricas
    ports:
      - "8001:8000"
    volumes:
      - ./metricas:/app

  generador_respuestas:
    build: ./generador_respuestas
    ports:
      - "8002:8000"

  cache_system:
    build: ./cache_system
    ports:
      - "8003:8000"
    depends_on:
      redis-cache:
        condition: service_healthy
      generador_respuestas:
        condition: service_started
      metricas:
        condition: service_started
    environment:
      - REDIS_HOST=redis-cache
      - RESPUESTAS_URL=http://generador_respuestas:8000
      - METRICAS_URL=http://metricas:8000

  generador_trafico:
    build: ./generador_trafico
    depends_on:
      - cache_system
    environment:
      - CACHE_URL=http://cache_system:8000
      - DISTRIBUCION=zipf
      - TOTAL_CONSULTAS=6000
      - SLEEP_ENTRE_CONSULTAS=0.01
      - CONFIDENCE_VARIATION=random
